services:
  bcso-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: bcso_front
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:80"
    depends_on:
      - bcso-api

  bcso-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bcso_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8089:5174"
    volumes:
      - ./persist-data:/app/data
